
services:
  next:
    build: .
    image: next-planillas
    container_name: next-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - red-apps

networks:
  red-apps:
    external: true


